apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-pvc-manager
  namespace: openebs
  labels:
    app: pvc-manager
    component: localpv-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openebs-pvc-manager
  labels:
    app: pvc-manager
    component: localpv-provisioner
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openebs-pvc-manager
  labels:
    app: pvc-manager
    component: localpv-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openebs-pvc-manager
subjects:
- kind: ServiceAccount
  name: openebs-pvc-manager
  namespace: openebs