name: Pull Request

on:
  pull_request:
    branches:
      - 'develop'
      - 'release/**'
  workflow_call:

jobs:
  preconditions:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.filter.outputs.relevant == 'true' || github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Detect relevant changes
        id: filter
        uses: dorny/paths-filter@v4
        with:
          predicate-quantifier: some-with-excludes
          filters: |
            relevant:
              - '**'
              - '!*.md'
              - '!changelogs/**'
              - '!docs/**'
              - '!design/**'
              - '!LICENSE'
              - '!MAINTAINERS'
  lint:
    uses: ./.github/workflows/lint.yml
    needs: ['preconditions']
    if: needs.preconditions.outputs.run == 'true'
    with:
      validate-codegen: true
      branch-name: ${{ github.event.pull_request.base.ref }}

  tests:
    needs: ['preconditions', 'lint']
    if: needs.preconditions.outputs.run == 'true'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  provisioner-localpv:
    runs-on: cncf-ubuntu-16-64-x86
    needs: ['preconditions', 'lint']
    if: needs.preconditions.outputs.run == 'true'
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: v0.13.1

      - name: Checkout
        uses: actions/checkout@v7

      - name: Build multi-arch Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./buildscripts/provisioner-localpv/provisioner-localpv.Dockerfile
          push: false
          load: false
          sbom: true
          provenance: mode=max
          platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/ppc64le
  ci:
    if: ${{ success() || needs.preconditions.outputs.run == 'false' }}
    needs:
      - preconditions
      - lint
      - tests
      - provisioner-localpv
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
